add option to create a sentinel file to trigger factory reset later
playtron-os/playtron-os-files pull request #58
Opened 2024-08-06 20:05 UTC by alkazar

2024-08-06 21:47 UTC, LukeShortCloud requested changes
Looks like there are some syntax issues. It's unrelated to this PR as it also appears in the `main` branch but we should probably fix that.

```
$ bash -n playtron-factory-reset 
playtron-factory-reset: line 74: syntax error near unexpected token `('
playtron-factory-reset: line 74: `rm -rf /var/!("home")'
```

2024-08-08 20:53 UTC, alkazar commented
> Looks like there are some syntax issues. It's unrelated to this PR as it also appears in the `main` branch but we should probably fix that.
> 
> ```
> $ bash -n playtron-factory-reset 
> playtron-factory-reset: line 74: syntax error near unexpected token `('
> playtron-factory-reset: line 74: `rm -rf /var/!("home")'
> ```

This is not an issue. That syntax requires `shopt -s exglob` but since the `-n` option doesn't execute any commands, that command is also not executed and the check fails.

Everything checks out if you use:
```
bash -O extglob -n playtron-factory-reset
```

2024-08-08 22:26 UTC, LukeShortCloud approved these changes

2024-08-08 22:26 UTC, LukeShortCloud commented
Thanks for the explanation!

2024-08-09 14:55 UTC, merged